
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.require_version ">= 1.5.0"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.define :master do |master|
    master.vm.provider :virtualbox do |v|
      v.name = "cloudera-dev-node1"
      v.customize ["modifyvm", :id, "--memory", "2048"]
      v.customize ['modifyvm', :id, '--cpus', 2]
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    end
    master.vm.network :private_network, ip: "192.168.2.85"
    master.vm.hostname = "hadoop-ner-1"
  end


  config.vm.provision "ansible" do |ansible|
    ansible.groups = {
      "dev" => ["default"],
      "nexus_access" => ["default"]
    }
    ansible.playbook = "vagrant.yml"
  end
end

